# Generated by Django 3.2.5 on 2021-07-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210703_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default=2, upload_to='productImages/'),
            preserve_default=False,
        ),
    ]
