# Generated by Django 3.2.5 on 2021-07-04 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='purchase',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
